kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "jobs-watcher-psp"
subjects:
- kind: ServiceAccount
  name: jobs-watcher
  namespace: "services"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
