kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-certmanager-certmanager-psp
  labels:
    app.kubernetes.io/name: cray-certmanager
subjects:
- kind: ServiceAccount
  name: cray-certmanager-cert-manager
  namespace: cert-manager
- kind: ServiceAccount
  name: cray-certmanager-cert-manager-cainjector
  namespace: cert-manager
- kind: ServiceAccount
  name: cray-certmanager-cert-manager-webhook
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
  apiGroup: rbac.authorization.k8s.io
