kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csmsshkeys-psp
subjects:
- kind: ServiceAccount
  name: csmsshkeys
  namespace: "services"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
