---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cray-postgres-operator-postgres-operator-ui-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
subjects:
- kind: ServiceAccount
  name: cray-postgres-operator-postgres-operator-ui
  namespace: services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cray-postgres-operator-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
subjects:
- kind: ServiceAccount
  name: postgres-pod
  namespace: services
- kind: ServiceAccount
  name: postgres-pod
  namespace: spire
- kind: ServiceAccount
  name: postgres-pod
  namespace: argo
- kind: ServiceAccount
  name: postgres-pod
  namespace: sma
