---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cray-crus-actor-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
subjects:
  - kind: ServiceAccount
    name: cray-crus-actor
    namespace: services
