apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restricted-transition-net-raw-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - restricted-transition-net-raw
  resources:
  - podsecuritypolicies
  verbs:
  - use
